
const myJson = {
    "dot_net": ".NET",
    "360-degree_video": "360 degree video",
    "3d_animation": "3D Animation",
    "3d_design": "3D Design",
    "3d_model_maker": "3D Model Maker",
    "3d_modelling": "3D Modelling",
    "3d_printing": "3D Printing",
    "3d_rendering": "3D Rendering",
    "3ds_max": "3ds Max",
    "4d": "4D",
    "academic_writing": "Academic Writing",
    "accounting": "Accounting",
    "actionscript": "ActionScript",
    "active_directory": "Active Directory",
    "ad_planning_buying": "Ad Planning / Buying",
    "adobe_air": "Adobe Air",
    "adobe_captivate": "Adobe Captivate",
    "adobe_dreamweaver": "Adobe Dreamweaver",
    "adobe_fireworks": "Adobe Fireworks",
    "adobe_flash": "Adobe Flash",
    "adobe_indesign": "Adobe InDesign",
    "adobe_lightroom": "Adobe Lightroom",
    "adobe_livecycle_designer": "Adobe LiveCycle Designer",
    "adobe_premiere_pro": "Adobe Premiere Pro",
    "advertisement_design": "Advertisement Design",
    "advertising": "Advertising",
    "aeronautical_engineering": "Aeronautical Engineering",
    "aerospace_engineering": "Aerospace Engineering",
    "affiliate_marketing": "Affiliate Marketing",
    "afrikaans": "Afrikaans",
    "after_effects": "After Effects",
    "agile_development": "Agile Development",
    "agronomy": "Agronomy",
    "air_conditioning": "Air Conditioning",
    "airbnb": "Airbnb",
    "ajax": "AJAX",
    "albanian": "Albanian",
    "algorithm": "Algorithm",
    "alibaba": "Alibaba",
    "amazon_fire": "Amazon Fire",
    "amazon_kindle": "Amazon Kindle",
    "amazon_web_services": "Amazon Web Services",
    "amqp": "AMQP",
    "analytics": "Analytics",
    "android": "Android",
    "android_honeycomb": "Android Honeycomb",
    "android_wear_sdk": "Android Wear SDK",
    "angular.js": "Angular.js",
    "animation": "Animation",
    "antenna_services": "Antenna Services",
    "anything_goes": "Anything Goes",
    "apache": "Apache",
    "apache_ant": "Apache Ant",
    "apache_solr": "Apache Solr",
    "app_designer": "App Designer",
    "app_developer": "App Developer",
    "appcelerator_titanium": "Appcelerator Titanium",
    "apple_compressor": "Apple Compressor",
    "apple_ibooks_author": "Apple iBooks Author",
    "apple_logic_pro": "Apple Logic Pro",
    "apple_motion": "Apple Motion",
    "apple_safari": "Apple Safari",
    "apple_watch": "Apple Watch",
    "applescript": "Applescript",
    "appliance_installation": "Appliance Installation",
    "appliance_repair": "Appliance Repair",
    "arabic": "Arabic",
    "arduino": "Arduino",
    "argus_monitoring_software": "Argus Monitoring Software",
    "article_rewriting": "Article Rewriting",
    "article_submission": "Article Submission",
    "articles": "Articles",
    "artificial_intelligence": "Artificial Intelligence",
    "arts_crafts": "Arts / Crafts",
    "as400_iseries": "AS400 / iSeries",
    "asbestos_removal": "Asbestos Removal",
    "asp": "ASP",
    "asp.net": "ASP.NET",
    "asphalt": "Asphalt",
    "assembly": "Assembly",
    "asterisk_pbx": "Asterisk PBX",
    "astrophysics": "Astrophysics",
    "attic_access_ladders": "Attic Access Ladders",
    "attorney": "Attorney",
    "audio_production": "Audio Production",
    "audio_services": "Audio Services",
    "audit": "Audit",
    "augmented_reality": "Augmented Reality",
    "autocad": "AutoCAD",
    "autodesk_inventor": "Autodesk Inventor",
    "autodesk_revit": "Autodesk Revit",
    "autohotkey": "AutoHotkey",
    "automotive": "Automotive",
    "autotask": "Autotask",
    "awnings": "Awnings",
    "axure": "Axure",
    "azure": "Azure",
    "backbone.js": "backbone.js",
    "balsamiq": "Balsamiq",
    "balustrading": "Balustrading",
    "bamboo_flooring": "Bamboo Flooring",
    "banner_design": "Banner Design",
    "basque": "Basque",
    "bathroom": "Bathroom",
    "bengali": "Bengali",
    "big_data": "Big Data",
    "bigcommerce": "BigCommerce",
    "binary_analysis": "Binary Analysis",
    "biology": "Biology",
    "biotechnology": "Biotechnology",
    "bitcoin": "Bitcoin",
    "biztalk": "Biztalk",
    "blackberry": "Blackberry",
    "blog": "Blog",
    "blog_design": "Blog Design",
    "blog_install": "Blog Install",
    "bluetooth_low_energy_ble": "Bluetooth Low Energy (BLE)",
    "bmc_remedy": "BMC Remedy",
    "book_artist": "Book Artist",
    "book_writing": "Book Writing",
    "bookkeeping": "Bookkeeping",
    "boonex_dolphin": "Boonex Dolphin",
    "bootstrap": "Bootstrap",
    "bosnian": "Bosnian",
    "bower": "Bower",
    "bpo": "BPO",
    "brackets": "Brackets",
    "brain_storming": "Brain Storming",
    "branding": "Branding",
    "bricklaying": "Bricklaying",
    "broadcast_engineering": "Broadcast Engineering",
    "brochure_design": "Brochure Design",
    "bsd": "BSD",
    "building": "Building",
    "building_architecture": "Building Architecture",
    "building_certifiers": "Building Certifiers",
    "building_consultants": "Building Consultants",
    "building_designer": "Building Designer",
    "building_surveyors": "Building Surveyors",
    "bulgarian": "Bulgarian",
    "bulk_marketing": "Bulk Marketing",
    "business_analysis": "Business Analysis",
    "business_cards": "Business Cards",
    "business_catalyst": "Business Catalyst",
    "business_coaching": "Business Coaching",
    "business_intelligence": "Business Intelligence",
    "business_plans": "Business Plans",
    "business_writing": "Business Writing",
    "buyer_sourcing": "Buyer Sourcing",
    "c_programming": "C Programming",
    "c#_programming": "C# Programming",
    "c++_programming": "C++ Programming",
    "cad_cam": "CAD/CAM",
    "cakephp": "CakePHP",
    "call_center": "Call Center",
    "call_control_xml": "Call Control XML",
    "capture_nx2": "Capture NX2",
    "caricature_cartoons": "Caricature / Cartoons",
    "carpentry": "Carpentry",
    "carpet_repair_laying": "Carpet Repair / Laying",
    "carports": "Carports",
    "cartography_maps": "Cartography / Maps",
    "carwashing": "Carwashing",
    "casperjs": "CasperJS",
    "cassandra": "Cassandra",
    "catalan": "Catalan",
    "catch_phrases": "Catch Phrases",
    "catia": "CATIA",
    "ceilings": "Ceilings",
    "cement_bonding_agents": "Cement Bonding Agents",
    "cgi": "CGI",
    "chef_configuration_management": "Chef Configuration Management",
    "chemical_engineering": "Chemical Engineering",
    "chordiant": "Chordiant",
    "christmas": "Christmas",
    "chrome_os": "Chrome OS",
    "cinema_4d": "Cinema 4D",
    "circuit_design": "Circuit Design",
    "cisco": "Cisco",
    "civil_engineering": "Civil Engineering",
    "classifieds_posting": "Classifieds Posting",
    "clean_technology": "Clean Technology",
    "cleaning_carpet": "Cleaning Carpet",
    "cleaning_domestic": "Cleaning Domestic",
    "cleaning_upholstery": "Cleaning Upholstery",
    "climate_sciences": "Climate Sciences",
    "clips": "CLIPS",
    "clothesline": "Clothesline",
    "cloud_computing": "Cloud Computing",
    "cms": "CMS",
    "coating_materials": "Coating Materials",
    "cobol": "COBOL",
    "cocoa": "Cocoa",
    "codeigniter": "Codeigniter",
    "coding": "Coding",
    "cold_fusion": "Cold Fusion",
    "columns": "Columns",
    "commercial_cleaning": "Commercial Cleaning",
    "commercials": "Commercials",
    "communications": "Communications",
    "compliance": "Compliance",
    "computer_graphics": "Computer Graphics",
    "computer_help": "Computer Help",
    "computer_security": "Computer Security",
    "concept_art": "Concept Art",
    "concept_design": "Concept Design",
    "concreting": "Concreting",
    "construction_monitoring": "Construction Monitoring",
    "content_writing": "Content Writing",
    "contracts": "Contracts",
    "conversion_rate_optimisation": "Conversion Rate Optimisation",
    "cooking_recipes": "Cooking / Recipes",
    "cooking_baking": "Cooking / Baking",
    "copy_typing": "Copy Typing",
    "copywriting": "Copywriting",
    "corporate_identity": "Corporate Identity",
    "courses": "Courses",
    "covers_packaging": "Covers / Packaging",
    "cre_loaded": "CRE Loaded",
    "creative_design": "Creative Design",
    "creative_writing": "Creative Writing",
    "crm": "CRM",
    "croatian": "Croatian",
    "cryptography": "Cryptography",
    "crystal_reports": "Crystal Reports",
    "cs-cart": "CS-Cart",
    "css": "CSS",
    "cubecart": "CubeCart",
    "cuda": "CUDA",
    "customer_service": "Customer Service",
    "customer_support": "Customer Support",
    "czech": "Czech",
    "damp_proofing": "Damp Proofing",
    "danish": "Danish",
    "dari": "Dari",
    "dart": "Dart",
    "data_entry": "Data Entry",
    "data_mining": "Data Mining",
    "data_processing": "Data Processing",
    "data_science": "Data Science",
    "data_warehousing": "Data Warehousing",
    "database_administration": "Database Administration",
    "database_development": "Database Development",
    "database_programming": "Database Programming",
    "datalife_engine": "DataLife Engine",
    "dating": "Dating",
    "dds": "DDS",
    "debian": "Debian",
    "debugging": "Debugging",
    "decking": "Decking",
    "decoration": "Decoration",
    "delivery": "Delivery",
    "delphi": "Delphi",
    "demolition": "Demolition",
    "design": "Design",
    "desktop_support": "Desktop Support",
    "digital_design": "Digital Design",
    "disposals": "Disposals",
    "django": "Django",
    "dns": "DNS",
    "dos": "DOS",
    "dotnetnuke": "DotNetNuke",
    "drafting": "Drafting",
    "drains": "Drains",
    "drones": "Drones",
    "drupal": "Drupal",
    "dthreejs": "Dthreejs",
    "dutch": "Dutch",
    "dynamics": "Dynamics",
    "ebay": "eBay",
    "ebooks": "eBooks",
    "ecommerce": "eCommerce",
    "editing": "Editing",
    "education_tutoring": "Education / Tutoring",
    "edx": "edX",
    "elasticsearch": "Elasticsearch",
    "elearning": "eLearning",
    "elearning_designer": "eLearning Designer",
    "electrical_engineering": "Electrical Engineering",
    "electricians": "Electricians",
    "electronic_forms": "Electronic Forms",
    "electronics": "Electronics",
    "email_developer": "Email Developer",
    "email_handling": "Email Handling",
    "email_marketing": "Email Marketing",
    "embedded_software": "Embedded Software",
    "ember.js": "Ember.js",
    "employment_law": "Employment Law",
    "energy": "Energy",
    "engineering": "Engineering",
    "engineering_drawing": "Engineering Drawing",
    "english_uk": "English (UK)",
    "english_us": "English (US)",
    "english_grammar": "English Grammar",
    "english_spelling": "English Spelling",
    "entrepreneurship": "Entrepreneurship",
    "epub": "ePub",
    "equipment_hire": "Equipment Hire",
    "erlang": "Erlang",
    "erp": "ERP",
    "estonian": "Estonian",
    "etsy": "Etsy",
    "event_planning": "Event Planning",
    "event_staffing": "Event Staffing",
    "excavation": "Excavation",
    "excel": "Excel",
    "express_js": "Express JS",
    "expression_engine": "Expression Engine",
    "extensions_additions": "Extensions / Additions",
    "face_recognition": "Face Recognition",
    "facebook_marketing": "Facebook Marketing",
    "fashion_design": "Fashion Design",
    "fashion_modeling": "Fashion Modeling",
    "fencing": "Fencing",
    "feng_shui": "Feng Shui",
    "fiction": "Fiction",
    "filemaker": "FileMaker",
    "filipino": "Filipino",
    "filmmaking": "Filmmaking",
    "final_cut_pro": "Final Cut Pro",
    "finale_sibelius": "Finale / Sibelius",
    "finance": "Finance",
    "financial_analysis": "Financial Analysis",
    "financial_markets": "Financial Markets",
    "financial_planning": "Financial Planning",
    "financial_research": "Financial Research",
    "finite_element_analysis": "Finite Element Analysis",
    "finnish": "Finnish",
    "firefox": "Firefox",
    "flash_3d": "Flash 3D",
    "flashmob": "Flashmob",
    "flex": "Flex",
    "floor_coatings": "Floor Coatings",
    "flooring": "Flooring",
    "flow_charts": "Flow Charts",
    "flyer_design": "Flyer Design",
    "flyscreens": "Flyscreens",
    "food_takeaway": "Food Takeaway",
    "format_layout": "Format / Layout",
    "fortran": "Fortran",
    "forum_posting": "Forum Posting",
    "forum_software": "Forum Software",
    "fpga": "FPGA",
    "frames_trusses": "Frames / Trusses",
    "freelance": "Freelance",
    "freelancerapi": "FreelancerAPI",
    "freeswitch": "FreeSwitch",
    "french": "French",
    "french_canadian": "French (Canadian)",
    "fundraising": "Fundraising",
    "furniture_assembly": "Furniture Assembly",
    "furniture_design": "Furniture Design",
    "game_consoles": "Game Consoles",
    "game_design": "Game Design",
    "game_development": "Game Development",
    "gamesalad": "GameSalad",
    "gamification": "Gamification",
    "garageband": "GarageBand",
    "gardening": "Gardening",
    "gas_fitting": "Gas Fitting",
    "genealogy": "Genealogy",
    "general_labor": "General Labor",
    "general_office": "General Office",
    "genetic_engineering": "Genetic Engineering",
    "geolocation": "Geolocation",
    "geology": "Geology",
    "geospatial": "Geospatial",
    "geotechnical_engineering": "Geotechnical Engineering",
    "german": "German",
    "ghostwriting": "Ghostwriting",
    "gimp": "GIMP",
    "git": "Git",
    "glass_mirror_glazing": "Glass / Mirror / Glazing",
    "golang": "Golang",
    "google_adsense": "Google Adsense",
    "google_adwords": "Google Adwords",
    "google_analytics": "Google Analytics",
    "google_app_engine": "Google App Engine",
    "google_cardboard": "Google Cardboard",
    "google_chrome": "Google Chrome",
    "google_cloud_storage": "Google Cloud Storage",
    "google_earth": "Google Earth",
    "google_maps_api": "Google Maps API",
    "google_plus": "Google Plus",
    "google_sketchup": "Google SketchUp",
    "google_web_toolkit": "Google Web Toolkit",
    "google_webmaster_tools": "Google Webmaster Tools",
    "google_website_optimizer": "Google Website Optimizer",
    "gopro": "GoPro",
    "gpgpu": "GPGPU",
    "gps": "GPS",
    "grails": "Grails",
    "grant_writing": "Grant Writing",
    "graphic_design": "Graphic Design",
    "grease_monkey": "Grease Monkey",
    "greek": "Greek",
    "growth_hacking": "Growth Hacking",
    "grunt": "Grunt",
    "guttering": "Guttering",
    "hadoop": "Hadoop",
    "hair_styles": "Hair Styles",
    "handyman": "Handyman",
    "haskell": "Haskell",
    "hbase": "HBase",
    "health": "Health",
    "heating_systems": "Heating Systems",
    "hebrew": "Hebrew",
    "helpdesk": "Helpdesk",
    "heroku": "Heroku",
    "hindi": "Hindi",
    "hire_me": "Hire me",
    "history": "History",
    "hive": "Hive",
    "home_automation": "Home Automation",
    "home_design": "Home Design",
    "home_organization": "Home Organization",
    "homekit": "HomeKit",
    "hot_water": "Hot Water",
    "house_cleaning": "House Cleaning",
    "housework": "Housework",
    "hp_openview": "HP Openview",
    "html": "HTML",
    "html5": "HTML5",
    "human_resources": "Human Resources",
    "human_sciences": "Human Sciences",
    "hungarian": "Hungarian",
    "ibeacon": "iBeacon",
    "ibm_bpm": "IBM BPM",
    "ibm_tivoli": "IBM Tivoli",
    "ibm_websphere_transformation_tool": "IBM Websphere Transformation Tool",
    "icon_design": "Icon Design",
    "iis": "IIS",
    "ikea_installation": "IKEA Installation",
    "illustration": "Illustration",
    "illustrator": "Illustrator",
    "imaging": "Imaging",
    "imovie": "iMovie",
    "indonesian": "Indonesian",
    "industrial_design": "Industrial Design",
    "industrial_engineering": "Industrial Engineering",
    "infographics": "Infographics",
    "inspections": "Inspections",
    "instagram": "Instagram",
    "installation": "Installation",
    "instrumentation": "Instrumentation",
    "insurance": "Insurance",
    "interior_design": "Interior Design",
    "interiors": "Interiors",
    "internet_marketing": "Internet Marketing",
    "internet_research": "Internet Research",
    "internet_security": "Internet Security",
    "interpreter": "Interpreter",
    "interspire": "Interspire",
    "intuit_quickbooks": "Intuit QuickBooks",
    "inventory_management": "Inventory Management",
    "investment_research": "Investment Research",
    "invitation_design": "Invitation Design",
    "ionic_framework": "Ionic Framework",
    "ipad": "iPad",
    "iphone": "iPhone",
    "iso9001": "ISO9001",
    "italian": "Italian",
    "itil": "ITIL",
    "j2ee": "J2EE",
    "j2me": "J2ME",
    "jabber": "Jabber",
    "japanese": "Japanese",
    "java": "Java",
    "javafx": "JavaFX",
    "javascript": "Javascript",
    "jd_edwards_cnc": "JD Edwards CNC",
    "jdf": "JDF",
    "jewellery": "Jewellery",
    "joomla": "Joomla",
    "journalist": "Journalist",
    "jquery_prototype": "jQuery / Prototype",
    "json": "JSON",
    "jsp": "JSP",
    "kannada": "Kannada",
    "kinect": "Kinect",
    "kitchen": "Kitchen",
    "knockout.js": "Knockout.js",
    "korean": "Korean",
    "label_design": "Label Design",
    "labview": "LabVIEW",
    "landing_pages": "Landing Pages",
    "landscape_design": "Landscape Design",
    "landscaping": "Landscaping",
    "landscaping_gardening": "Landscaping / Gardening",
    "laravel": "Laravel",
    "latex": "LaTeX",
    "latvian": "Latvian",
    "laundry_and_ironing": "Laundry and Ironing",
    "lawn_mowing": "Lawn Mowing",
    "leads": "Leads",
    "leap_motion_sdk": "Leap Motion SDK",
    "legal": "Legal",
    "legal_research": "Legal Research",
    "legal_writing": "Legal Writing",
    "less_sass_scss": "LESS/Sass/SCSS",
    "life_coaching": "Life Coaching",
    "lighting": "Lighting",
    "linear_programming": "Linear Programming",
    "link_building": "Link Building",
    "linkedin": "Linkedin",
    "linnworks_order_management": "Linnworks Order Management",
    "linq": "LINQ",
    "linux": "Linux",
    "lisp": "Lisp",
    "lithuanian": "Lithuanian",
    "livecode": "LiveCode",
    "locksmith": "Locksmith",
    "logistics_shipping": "Logistics / Shipping",
    "logo_design": "Logo Design",
    "lotus_notes": "Lotus Notes",
    "lua": "Lua",
    "mac_os": "Mac OS",
    "macedonian": "Macedonian",
    "machine_learning": "Machine Learning",
    "magento": "Magento",
    "magic_leap": "Magic Leap",
    "mailchimp": "Mailchimp",
    "mailwizz": "Mailwizz",
    "make_up": "Make Up",
    "makerbot": "Makerbot",
    "malay": "Malay",
    "malayalam": "Malayalam",
    "maltese": "Maltese",
    "management": "Management",
    "manufacturing": "Manufacturing",
    "manufacturing_design": "Manufacturing Design",
    "map_reduce": "Map Reduce",
    "mariadb": "MariaDB",
    "market_research": "Market Research",
    "marketing": "Marketing",
    "marketplace_service": "Marketplace Service",
    "materials_engineering": "Materials Engineering",
    "mathematics": "Mathematics",
    "matlab_and_mathematica": "Matlab and Mathematica",
    "maya": "Maya",
    "mechanical_engineering": "Mechanical Engineering",
    "mechatronics": "Mechatronics",
    "medical": "Medical",
    "medical_writing": "Medical Writing",
    "metatrader": "Metatrader",
    "meteorjs": "MeteorJS",
    "metro": "Metro",
    "microbiology": "Microbiology",
    "microcontroller": "Microcontroller",
    "microsoft": "Microsoft",
    "microsoft_access": "Microsoft Access",
    "microsoft_exchange": "Microsoft Exchange",
    "microsoft_expression": "Microsoft Expression",
    "microsoft_hololens": "Microsoft Hololens",
    "microsoft_office": "Microsoft Office",
    "microsoft_outlook": "Microsoft Outlook",
    "microsoft_sql_server": "Microsoft SQL Server",
    "microsoft_visio": "Microsoft Visio",
    "microstation": "Microstation",
    "millwork": "Millwork",
    "mining_engineering": "Mining Engineering",
    "minitlab": "Minitlab",
    "mlm": "MLM",
    "mmorpg": "MMORPG",
    "mobile_app_testing": "Mobile App Testing",
    "mobile_phone": "Mobile Phone",
    "modx": "MODx",
    "monetdb": "MonetDB",
    "moodle": "Moodle",
    "mortgage_brokering": "Mortgage Brokering",
    "motion_graphics": "Motion Graphics",
    "moving": "Moving",
    "mqtt": "MQTT",
    "mural_painting": "Mural Painting",
    "music": "Music",
    "mvc": "MVC",
    "myob": "MYOB",
    "myspace": "MySpace",
    "mysql": "MySQL",
    "nanotechnology": "Nanotechnology",
    "natural_language": "Natural Language",
    "network_administration": "Network Administration",
    "newsletters": "Newsletters",
    "nginx": "Nginx",
    "ning": "Ning",
    "nintex_forms": "Nintex Forms",
    "nintex_workflow": "Nintex Workflow",
    "node.js": "node.js",
    "nokia": "Nokia",
    "norwegian": "Norwegian",
    "nosql_couch_mongo": "NoSQL Couch / Mongo",
    "nutrition": "Nutrition",
    "oauth": "OAuth",
    "objective_c": "Objective C",
    "ocr": "OCR",
    "oculus_mobile_sdk": "Oculus Mobile SDK",
    "odoo": "Odoo",
    "online_writing": "Online Writing",
    "open_cart": "Open Cart",
    "open_journal_systems": "Open Journal Systems",
    "openbravo": "OpenBravo",
    "opencl": "OpenCL",
    "opengl": "OpenGL",
    "openscenegraph": "OpenSceneGraph",
    "openssl": "OpenSSL",
    "openstack": "OpenStack",
    "openvms": "OpenVMS",
    "oracle": "Oracle",
    "order_processing": "Order Processing",
    "organizational_change_management": "Organizational Change Management",
    "oscommerce": "OSCommerce",
    "package_design": "Package Design",
    "packing_shipping": "Packing / Shipping",
    "painting": "Painting",
    "palm": "Palm",
    "papiamento": "Papiamento",
    "parallax_scrolling": "Parallax Scrolling",
    "parallel_processing": "Parallel Processing",
    "parallels_automation": "Parallels Automation",
    "parallels_desktop": "Parallels Desktop",
    "patents": "Patents",
    "pattern_making": "Pattern Making",
    "pattern_matching": "Pattern Matching",
    "pavement": "Pavement",
    "paypal_api": "PayPal API",
    "payroll": "Payroll",
    "paytrace": "Paytrace",
    "pcb_layout": "PCB Layout",
    "pdf": "PDF",
    "pega_prpc": "PEGA PRPC",
    "pencilblue_cms": "PencilBlue CMS",
    "pentaho": "Pentaho",
    "peoplesoft": "PeopleSoft",
    "periscope": "Periscope",
    "perl": "Perl",
    "personal_development": "Personal Development",
    "pest_control": "Pest Control",
    "pet_sitting": "Pet Sitting",
    "petroleum_engineering": "Petroleum Engineering",
    "phone_support": "Phone Support",
    "phonegap": "PhoneGap",
    "photo_editing": "Photo Editing",
    "photography": "Photography",
    "photoshop": "Photoshop",
    "photoshop_coding": "Photoshop Coding",
    "photoshop_design": "Photoshop Design",
    "php": "PHP",
    "physics": "Physics",
    "pick_multivalue_db": "PICK Multivalue DB",
    "pickup": "Pickup",
    "pinterest": "Pinterest",
    "piping": "Piping",
    "plc_scada": "PLC / SCADA",
    "plesk": "Plesk",
    "plugin": "Plugin",
    "plumbing": "Plumbing",
    "poet": "Poet",
    "poetry": "Poetry",
    "polish": "Polish",
    "portuguese": "Portuguese",
    "portuguese_brazil": "Portuguese (Brazil)",
    "post-production": "Post-Production",
    "poster_design": "Poster Design",
    "postgresql": "PostgreSQL",
    "powerpoint": "Powerpoint",
    "powershell": "Powershell",
    "pre-production": "Pre-production",
    "presentations": "Presentations",
    "press_releases": "Press Releases",
    "prestashop": "Prestashop",
    "prezi": "Prezi",
    "print": "Print",
    "procurement": "Procurement",
    "product_descriptions": "Product Descriptions",
    "product_design": "Product Design",
    "product_management": "Product Management",
    "product_sourcing": "Product Sourcing",
    "programming": "Programming",
    "project_management": "Project Management",
    "project_scheduling": "Project Scheduling",
    "prolog": "Prolog",
    "proofreading": "Proofreading",
    "property_development": "Property Development",
    "property_law": "Property Law",
    "property_management": "Property Management",
    "proposal_bid_writing": "Proposal/Bid Writing",
    "protoshare": "Protoshare",
    "psd_to_html": "PSD to HTML",
    "psd2cms": "PSD2CMS",
    "psychology": "Psychology",
    "public_relations": "Public Relations",
    "publishing": "Publishing",
    "punjabi": "Punjabi",
    "puppet": "Puppet",
    "python": "Python",
    "qlikview": "QlikView",
    "qualtrics_survey_platform": "Qualtrics Survey Platform",
    "quantum": "Quantum",
    "quarkxpress": "QuarkXPress",
    "quickbase": "QuickBase",
    "r_programming_language": "R Programming Language",
    "rapidweaver": "RapidWeaver",
    "raspberry_pi": "Raspberry Pi",
    "ray-tracing": "Ray-tracing",
    "react.js": "React.js",
    "real_estate": "Real Estate",
    "realbasic": "REALbasic",
    "recruitment": "Recruitment",
    "red_hat": "Red Hat",
    "redis": "Redis",
    "redshift": "Redshift",
    "regular_expressions": "Regular Expressions",
    "remote_sensing": "Remote Sensing",
    "removalist": "Removalist",
    "renewable_energy_design": "Renewable Energy Design",
    "report_writing": "Report Writing",
    "research": "Research",
    "restful": "RESTful",
    "resumes": "Resumes",
    "reviews": "Reviews",
    "risk_management": "Risk Management",
    "robotics": "Robotics",
    "rocket_engine": "Rocket Engine",
    "romanian": "Romanian",
    "roofing": "Roofing",
    "rtos": "RTOS",
    "ruby": "Ruby",
    "ruby_on_rails": "Ruby on Rails",
    "russian": "Russian",
    "rwd": "RWD",
    "sales": "Sales",
    "salesforce_app_development": "Salesforce App Development",
    "salesforce.com": "Salesforce.com",
    "samsung": "Samsung",
    "samsung_accessory_sdk": "Samsung Accessory SDK",
    "sap": "SAP",
    "sas": "SAS",
    "scala": "Scala",
    "scheme": "Scheme",
    "scientific_research": "Scientific Research",
    "screenwriting": "Screenwriting",
    "script_install": "Script Install",
    "scrum": "Scrum",
    "scrum_development": "Scrum Development",
    "sculpturing": "Sculpturing",
    "search_engine_marketing": "Search Engine Marketing",
    "sencha_yahooui": "Sencha / YahooUI",
    "seo": "SEO",
    "serbian": "Serbian",
    "sewing": "Sewing",
    "sharepoint": "Sharepoint",
    "shell_script": "Shell Script",
    "shopify": "Shopify",
    "shopify_templates": "Shopify Templates",
    "shopping": "Shopping",
    "shopping_carts": "Shopping Carts",
    "short_stories": "Short Stories",
    "siebel": "Siebel",
    "sign_design": "Sign Design",
    "silverlight": "Silverlight",
    "simplified_chinese_china": "Simplified Chinese (China)",
    "slogans": "Slogans",
    "slovakian": "Slovakian",
    "slovenian": "Slovenian",
    "smarty_php": "Smarty PHP",
    "snapchat": "Snapchat",
    "social_engine": "Social Engine",
    "social_media_marketing": "Social Media Marketing",
    "social_networking": "Social Networking",
    "socket_io": "Socket IO",
    "software_architecture": "Software Architecture",
    "software_development": "Software Development",
    "software_testing": "Software Testing",
    "solaris": "Solaris",
    "solidworks": "Solidworks",
    "sound_design": "Sound Design",
    "spanish": "Spanish",
    "spanish_spain": "Spanish (Spain)",
    "spark": "Spark",
    "speech_writing": "Speech Writing",
    "sphinx": "Sphinx",
    "splunk": "Splunk",
    "sports": "Sports",
    "spss_statistics": "SPSS Statistics",
    "sql": "SQL",
    "sqlite": "SQLite",
    "squarespace": "Squarespace",
    "squid_cache": "Squid Cache",
    "startups": "Startups",
    "stationery_design": "Stationery Design",
    "statistical_analysis": "Statistical Analysis",
    "statistics": "Statistics",
    "steam_api": "Steam API",
    "sticker_design": "Sticker Design",
    "storage_area_networks": "Storage Area Networks",
    "storyboard": "Storyboard",
    "stripe": "Stripe",
    "structural_engineering": "Structural Engineering",
    "subversion": "Subversion",
    "sugarcrm": "SugarCRM",
    "supplier_sourcing": "Supplier Sourcing",
    "surfboard_design": "Surfboard Design",
    "swedish": "Swedish",
    "swift": "Swift",
    "symbian": "Symbian",
    "symfony_php": "Symfony PHP",
    "system_admin": "System Admin",
    "t-shirts": "T-Shirts",
    "tableau": "Tableau",
    "tally_definition_language": "Tally Definition Language",
    "tamil": "Tamil",
    "taobao_api": "TaoBao API",
    "tattoo_design": "Tattoo Design",
    "tax": "Tax",
    "tax_law": "Tax Law",
    "technical_support": "Technical Support",
    "technical_writing": "Technical Writing",
    "tekla_structures": "Tekla Structures",
    "telecommunications_engineering": "Telecommunications Engineering",
    "telemarketing": "Telemarketing",
    "telephone_handling": "Telephone Handling",
    "telugu": "Telugu",
    "templates": "Templates",
    "test_automation": "Test Automation",
    "testing_qa": "Testing / QA",
    "teststand": "TestStand",
    "textile_engineering": "Textile Engineering",
    "thai": "Thai",
    "tibco_spotfire": "Tibco Spotfire",
    "tiling": "Tiling",
    "time_management": "Time Management",
    "titanium": "Titanium",
    "tizen_sdk_for_wearables": "Tizen SDK for Wearables",
    "traditional_chinese_hong_kong": "Traditional Chinese (Hong Kong)",
    "traditional_chinese_taiwan": "Traditional Chinese (Taiwan)",
    "training": "Training",
    "transcription": "Transcription",
    "translation": "Translation",
    "travel_writing": "Travel Writing",
    "troubleshooting": "Troubleshooting",
    "tumblr": "Tumblr",
    "turkish": "Turkish",
    "twitter": "Twitter",
    "typescript": "Typescript",
    "typo3": "TYPO3",
    "typography": "Typography",
    "ubuntu": "Ubuntu",
    "ukrainian": "Ukrainian",
    "umbraco": "Umbraco",
    "uml_design": "UML Design",
    "unit4_business_world": "Unit4 Business World",
    "unity_3d": "Unity 3D",
    "unix": "UNIX",
    "urdu": "Urdu",
    "usability_testing": "Usability Testing",
    "user_experience_design": "User Experience Design",
    "user_interface_ia": "User Interface / IA",
    "user_interface_design": "User Interface Design",
    "valuation_appraisal": "Valuation / Appraisal",
    "varnish_cache": "Varnish Cache",
    "vb.net": "VB.NET",
    "vbulletin": "vBulletin",
    "vectorization": "Vectorization",
    "veeam": "Veeam",
    "vehicle_signage": "Vehicle Signage",
    "verilog": "Verilog",
    "vhdl": "VHDL",
    "vertexfx": "VertexFX",
    "video_broadcasting": "Video Broadcasting",
    "video_editing": "Video Editing",
    "video_production": "Video Production",
    "video_services": "Video Services",
    "video_upload": "Video Upload",
    "videography": "Videography",
    "vietnamese": "Vietnamese",
    "viral_marketing": "Viral Marketing",
    "virtual_assistant": "Virtual Assistant",
    "virtual_worlds": "Virtual Worlds",
    "virtuemart": "Virtuemart",
    "virtuozzo": "Virtuozzo",
    "visa_immigration": "Visa / Immigration",
    "visual_arts": "Visual Arts",
    "visual_basic": "Visual Basic",
    "visual_basic_for_apps": "Visual Basic for Apps",
    "visual_foxpro": "Visual Foxpro",
    "visual_merchandising": "Visual Merchandising",
    "visualization": "Visualization",
    "vmware": "VMware",
    "voice_artist": "Voice Artist",
    "voice_talent": "Voice Talent",
    "voicexml": "VoiceXML",
    "voip": "VoIP",
    "volusion": "Volusion",
    "vps": "VPS",
    "vtiger": "vTiger",
    "vuforia": "Vuforia",
    "watchkit": "WatchKit",
    "web_hosting": "Web Hosting",
    "web_scraping": "Web Scraping",
    "web_search": "Web Search",
    "web_security": "Web Security",
    "web_services": "Web Services",
    "webmethods": "webMethods",
    "webos": "WebOS",
    "website_design": "Website Design",
    "website_management": "Website Management",
    "website_testing": "Website Testing",
    "weddings": "Weddings",
    "weebly": "Weebly",
    "welsh": "Welsh",
    "whmcs": "WHMCS",
    "wiki": "WIKI",
    "wikipedia": "Wikipedia",
    "windows_8": "Windows 8",
    "windows_api": "Windows API",
    "windows_ce": "Windows CE",
    "windows_desktop": "Windows Desktop",
    "windows_mobile": "Windows Mobile",
    "windows_phone": "Windows Phone",
    "windows_server": "Windows Server",
    "wireframes": "Wireframes",
    "wireless": "Wireless",
    "wix": "Wix",
    "wolfram": "Wolfram",
    "woocommerce": "WooCommerce",
    "word": "Word",
    "word_processing": "Word Processing",
    "wordpress": "WordPress",
    "workshops": "Workshops",
    "wpf": "WPF",
    "wufoo": "Wufoo",
    "x86_x64_assembler": "x86/x64 Assembler",
    "xamarin": "Xamarin",
    "xero": "Xero",
    "xml": "XML",
    "xmpp": "XMPP",
    "xojo": "Xojo",
    "xoops": "Xoops",
    "xpages": "XPages",
    "xquery": "XQuery",
    "xslt": "XSLT",
    "yahoo!_store_design": "Yahoo! Store Design",
    "yard_work_removal": "Yard Work / Removal",
    "yarn": "Yarn",
    "yiddish": "Yiddish",
    "yii": "Yii",
    "youtube": "YouTube",
    "zbrush": "Zbrush",
    "zen_cart": "Zen Cart",
    "zend": "Zend",
    "zendesk": "Zendesk",
    "zoho": "Zoho"
}

export const values = Object.values(myJson);
export const frontEndSkills = [
    'HTML (HyperText Markup Language)',
    'CSS (Cascading Style Sheets)',
    'JavaScript',
    'jQuery',
    'React.js',
    'Angular.js',
    'Vue.js',
    'svelte',
    'Front-End Frameworks (e.g., Bootstrap, Material-UI)',
    'CSS Preprocessors (e.g., Sass, Less)',
    'RESTful Services/APIs',
    'Responsive/Mobile Design',
    'Cross-Browser Development',
    'Content Management Systems (CMS)',
    'Web Accessibility (WCAG)',
    'Testing/Debugging',
    'Git/Version Control',
    'Problem-Solving',
    "React",
    "Angular",
    "Vue.js",
    "Svelte",
    "Ember.js",
    "Mithril",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Astro"
];




export function showSuggestions(userInput, suggestionBox, setAtribute) {

    suggestionBox.innerHTML = "";
    console.log(userInput)

    const filteredItems = values.filter(item => item.toLowerCase().startsWith(userInput.toLowerCase()));


    if (filteredItems.length > 0 && userInput.length > 0) {
        filteredItems.forEach(item => {
            const suggestionElement = document.createElement("button");
            suggestionElement.addEventListener('click', () => setAtribute(item))
            suggestionElement.textContent = item;
            suggestionBox.appendChild(suggestionElement);
        });

    } else {
        const noSuggestionElement = document.createElement("li");
        noSuggestionElement.textContent = "No suggestions found";
        suggestionBox.appendChild(noSuggestionElement);
    }
}
